version: '3.8'

services:
    app:
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - chromadb
        environment:
            - CHROMA_HOST=chromadb
            - CHROMA_PORT=8000

    chromadb:
        image: chromadb/chroma
        ports:
            - "8001:8000"
        volumes:
            - chroma_data:/chroma/chroma


volumes:
    chroma_data:

